Report tests into Github

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -25,6 +25,14 @@ jobs:
           echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc && \
           npm ci
 
-      - name: Run tests
+      - name: Run Tests
         run: |
-          xvfb-run npm run test
+          xvfb-run npm run testToJsonFile
+
+      - name: Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()     # run this step even if previous step failed
+        with:
+          name: Mocha Tests            # Name of the check run which will be created
+          path: out/tests-report.json  # Path to test results
+          reporter: mocha-json         # Format of test results
